# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/jessie64"
  config.ssh.insert_key = false
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/fwsl/xenorchestra_installer/master/xo_install.sh"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.define "xo-test" do |ec8_auth|
    ec8_auth.vm.network :private_network, ip: "10.11.12.13"
    ec8_auth.vm.hostname = "xo-test"
    ec8_auth.hostsupdater.aliases = ["xo-test.local"]
  end  
  
end
